import type { Restroom } from "./types";

export const MOCK_RESTROOMS: Restroom[] = [
	{
		restroomId: "MM102",
		name: "Main Men's 1F",
		building: "Main",
		floor: 1,
		gender: "male",
		pwdAccessible: true,
		tags: ["soapPump", "vending"],
		stallCount: 5,
		reviewCount: 8,
		ratings: {
			cleanliness: 4,
			smell: 4,
			privacy: 4,
			comfort: 4.5,
			accessibility: 4,
		},
	},
	{
		restroomId: "WM301",
		name: "West Men's 3F Lounge",
		building: "West",
		floor: 3,
		gender: "male",
		pwdAccessible: false,
		tags: ["soapPump"],
		stallCount: 4,
		reviewCount: 6,
		ratings: {
			cleanliness: 4.5,
			smell: 4.5,
			privacy: 4,
			comfort: 4,
			accessibility: 3,
		},
	},
	{
		restroomId: "WM102",
		name: "West Men's 1F Lobby",
		building: "West",
		floor: 1,
		gender: "male",
		pwdAccessible: true,
		tags: ["soapPump", "bidet"],
		stallCount: 3,
		reviewCount: 3,
		ratings: {
			cleanliness: 4,
			smell: 3.5,
			privacy: 3.5,
			comfort: 3.5,
			accessibility: 4.5,
		},
	},
	{
		restroomId: "WF201",
		name: "West Women's 2F",
		building: "West",
		floor: 2,
		gender: "female",
		pwdAccessible: false,
		tags: ["soapPump", "seatCover"],
		stallCount: 5,
		reviewCount: 12,
		ratings: {
			cleanliness: 5,
			smell: 4.5,
			privacy: 4.5,
			comfort: 4.5,
			accessibility: 3.5,
		},
	},
	{
		restroomId: "NM303",
		name: "North Men's 3F",
		building: "North",
		floor: 3,
		gender: "male",
		pwdAccessible: false,
		tags: ["vending"],
		stallCount: 4,
		reviewCount: 2,
		ratings: {
			cleanliness: 3.5,
			smell: 3,
			privacy: 3.5,
			comfort: 3.5,
			accessibility: 3,
		},
	},
	{
		restroomId: "NF101",
		name: "North Women's 1F",
		building: "North",
		floor: 1,
		gender: "female",
		pwdAccessible: true,
		tags: ["soapPump"],
		stallCount: 3,
		reviewCount: 5,
		ratings: {
			cleanliness: 4,
			smell: 4,
			privacy: 4.5,
			comfort: 4,
			accessibility: 4.5,
		},
	},
	{
		restroomId: "NA204",
		name: "North All-Gender 2F",
		building: "North",
		floor: 2,
		gender: "all-gender",
		pwdAccessible: true,
		tags: ["bidet", "seatCover", "soapPump"],
		stallCount: 2,
		reviewCount: 15,
		ratings: {
			cleanliness: 5,
			smell: 4.5,
			privacy: 5,
			comfort: 4.5,
			accessibility: 4.5,
		},
	},
	{
		restroomId: "SM401",
		name: "South Men's 4F",
		building: "South",
		floor: 4,
		gender: "male",
		pwdAccessible: false,
		tags: ["vending", "soapPump"],
		stallCount: 6,
		reviewCount: 4,
		ratings: {
			cleanliness: 3,
			smell: 3,
			privacy: 3.5,
			comfort: 3.5,
			accessibility: 3,
		},
	},
	{
		restroomId: "SF202",
		name: "South Women's 2F",
		building: "South",
		floor: 2,
		gender: "female",
		pwdAccessible: false,
		tags: ["seatCover"],
		stallCount: 4,
		reviewCount: 0,
		ratings: null,
	},
	{
		restroomId: "NM501",
		name: "North Men's 5F",
		building: "North",
		floor: 5,
		gender: "male",
		pwdAccessible: false,
		tags: [],
		stallCount: 4,
		reviewCount: 0,
		ratings: null,
	},
	{
		restroomId: "MA302",
		name: "Main All-Gender 3F",
		building: "Main",
		floor: 3,
		gender: "all-gender",
		pwdAccessible: true,
		tags: ["bidet", "vending", "soapPump"],
		stallCount: 3,
		reviewCount: 9,
		ratings: {
			cleanliness: 4.5,
			smell: 5,
			privacy: 4.5,
			comfort: 4.5,
			accessibility: 4.5,
		},
	},
];
